-- Delete old video lessons
DELETE FROM public.content WHERE type = 'video' AND subject IN ('Herrega', 'Saayinsii');

-- Insert new Herrega video lessons
INSERT INTO public.content (title, type, url, grade_level, subject) VALUES
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 1', 'video', 'https://youtu.be/IOStKmgYxfw?si=Trd_TPT-MptcBb9u', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 2', 'video', 'https://youtu.be/hRynU53AogY?si=Mq5aiilwVs3AwsWU', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 3', 'video', 'https://youtu.be/yLkN2p5sWPk?si=lBXib5xV863pwkzU', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 4', 'video', 'https://youtu.be/K1JlrHLzSyo?si=lojiPN-qOdoXBoUN', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 5', 'video', 'https://youtu.be/YYY2p_71i7c?si=-bYIZasXzcBx9lIw', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 6', 'video', 'https://youtu.be/Njw7nlEc8ac?si=w_9R2C53d8RPKkXY', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 7', 'video', 'https://youtu.be/ElkNorsPlHY?si=-FNfG2zlmNaEYfPa', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 8', 'video', 'https://youtu.be/CNg8Hvp-exI?si=HAi8-RtuxNJNkRZR', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 9', 'video', 'https://youtu.be/ClyAfvah1hM?si=KA1fF2C7bNKblky5', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 10', 'video', 'https://youtu.be/cV7u0dlgYEo?si=lzkpBmk4MOtB5kab', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 11', 'video', 'https://youtu.be/qS9qpdcZHB4?si=kCyF8nBvmPL5Dk-Q', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 12', 'video', 'https://youtu.be/ck-NnzaB9R8?si=QKfaZESErIG0cerg', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 13', 'video', 'https://youtu.be/RCbgnuPpqjM?si=oXjZ9aYKXa2Qh6xz', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 14', 'video', 'https://youtu.be/DPYcs-cUZB4?si=_8kRZXk1LC5IG9w3', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 15', 'video', 'https://youtu.be/NgN4fm6Dkd8?si=LzgaIBOAFwgNAv1k', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 16', 'video', 'https://youtu.be/2ENOnK9HSJ0?si=L_8YTXicekYq5xRS', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 17', 'video', 'https://youtu.be/2ENOnK9HSJ0?si=L_8YTXicekYq5xRS', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 18', 'video', 'https://youtu.be/3ElG7oBp_2U?si=US5gC9uHXToPCEqR', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 19', 'video', 'https://youtu.be/QVqTc7BObvE?si=-3Dq8JnIAmTZ1i4y', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 20', 'video', 'https://youtu.be/KhtlLcUKBOo?si=KH8SffUPIGmROkEt', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 21', 'video', 'https://youtu.be/SxbkUyUVpQc?si=qmutgAMlzQ8wNK9O', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 22', 'video', 'https://youtu.be/XMiI3xRfVis?si=mpkl9-f1s7vZwxm4', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 1ffaa part 23 final', 'video', 'https://youtu.be/hLuwonuG_g4?si=I_hg9xR5qwzwAVDj', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 1', 'video', 'https://youtu.be/gmZa1Gq7ZkI?si=caqTqoegM21L-Sel', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 2', 'video', 'https://youtu.be/laI93C_mv1w?si=ii11G_vmrTj9bXys', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 3', 'video', 'https://youtu.be/ks0m4Uo1NLA?si=d--Z5E_fj3crX5_z', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 4', 'video', 'https://youtu.be/qY4zxXkPyOA?si=-OmcflVtzJfDSGAb', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 5', 'video', 'https://youtu.be/7gil_2toTU8?si=hyXFY72Er7rn63iF', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 6', 'video', 'https://youtu.be/tM-WkTGN0ms?si=4R9sHhlRLbMhi0VE', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 7', 'video', 'https://youtu.be/Ce7q9w6wBxA?si=p-2ZNJ_bt0K9LDvu', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 8', 'video', 'https://youtu.be/RudJ-Q9gwls?si=9tdSotpIEG2Pt5tq', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 9', 'video', 'https://youtu.be/GzDAWxhBFh0?si=dRFBHKDnq3iY2EGR', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 10', 'video', 'https://youtu.be/9FRLxctUrJ4?si=xMPHO3m6ixBIkZ58', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 11', 'video', 'https://youtu.be/PDqHlzVqHYw?si=iUxufK26QZyT7U0C', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 12', 'video', 'https://youtu.be/oPevvphCr5Q?si=9uJIGckbaI-VGLPE', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 13', 'video', 'https://youtu.be/RIImvRQkBcc?si=UsZKgA2R-Tn-NHpj', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 14', 'video', 'https://youtu.be/jYnFf_mrPwA?si=nfJGG-23HQkNIoiQ', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 15', 'video', 'https://youtu.be/innA9t0pUr4?si=Xs04GBlYS4Fznc93', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 16', 'video', 'https://youtu.be/mlygu7SjAr0?si=CmBETPSVhNNynC4b', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 17', 'video', 'https://youtu.be/zEl8rI49lYQ?si=eBSVB5ip4Zax6m66', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 18', 'video', 'https://youtu.be/vI78B7a3EY4?si=48__PyuKQXgOUFph', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 19', 'video', 'https://youtu.be/aHNiFv3QTq4?si=oFxVBRfl46UEjmGD', 'Grade 8', 'Herrega'),
('Herrega kutaa 8ffaa boqonnaa 2ffaa part 20 final', 'video', 'https://youtu.be/ftBleS9xzkk?si=FQpfoUz-_BFzTy59', 'Grade 8', 'Herrega'),
('Saayinsii waligalaa boqonnaa 1ffaa part 1', 'video', 'https://youtu.be/k2QCKoTSCSw?si=MRsxdS5P6kl2H2Eh', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 2', 'video', 'https://youtu.be/W3CkdVQdZ7c?si=n144DgU-I5a90KfO', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 3', 'video', 'https://youtu.be/CqfY_RJfVwA?si=wkYe9zZrEwE9AUuZ', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 4', 'video', 'https://youtu.be/xhSLOqG-6T0?si=wknSBhjeaHzHn6zq', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 5', 'video', 'https://youtu.be/Jf4CS1WWf2E?si=KTti76zFcABzRgQz', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 6', 'video', 'https://youtu.be/ZzZNZf0HPuY?si=ZnVLaM6H1v_YzqXV', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 7', 'video', 'https://youtu.be/EZLFThCbcdY?si=kr3oFzwmZVFri75E', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 8', 'video', 'https://youtu.be/1txrv11CYfo?si=0mecbiEszlQimDtf', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 9', 'video', 'https://youtu.be/0n1CicY7f2E?si=eDIe_WIQF3mIMxzN', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 10', 'video', 'https://youtu.be/LcowLtaUcOA?si=P1K3D_IKTtJurFJj', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 11', 'video', 'https://youtu.be/oj3X2u9ZoQM?si=uf-QBqrbjB-dJQ59', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 12', 'video', 'https://youtu.be/9zPE_ja3mRs?si=WhtowK13zymrwU2s', 'Grade 8', 'Saayinsii'),
('Saayinsii waligalaa boqonnaa 1ffaa part 13', 'video', 'https://youtu.be/EZLFThCbcdY?si=h7FJkWkEI0BwzooG', 'Grade 8', 'Saayinsii');

-- Insert digital books
INSERT INTO public.content (title, description, type, url, grade_level, subject) VALUES
('Kitaaba hawaasa kutaa 8ffaa', 'Digital textbook for Hawaasa - Grade 8', 'pdf', 'https://drive.google.com/file/d/1EWvzSdty1Ns13vQ-VIQx2oNctSc5hvfc/view?usp=drivesdk', 'Grade 8', 'Hawaasa'),
('Kitaaba herrega kutaa 8ffaa', 'Digital textbook for Herrega - Grade 8', 'pdf', 'https://drive.google.com/file/d/1x6gCnwXse7dyf4d90ytl3pQLeVLMdhVp/view?usp=drivesdk', 'Grade 8', 'Herrega'),
('Kitaaba lammummaa kutaa 8ffaa', 'Digital textbook for Lammummaa - Grade 8', 'pdf', 'https://drive.google.com/file/d/1JEaZKSAsW23cnYMt89ALC0v8QX9i_d0E/view?usp=drivesdk', 'Grade 8', 'Lammummaa'),
('Kitaaba ingiliffaa kutaa 8ffaa', 'Digital textbook for English - Grade 8', 'pdf', 'https://drive.google.com/file/d/1rbWCJfemAC9wOas4W99EoQkaB5OWzyyF/view?usp=drivesdk', 'Grade 8', 'Ingiliffaa'),
('Kitaaba afaan oromoo kutaa 8ffaa', 'Digital textbook for Afaan Oromoo - Grade 8', 'pdf', 'https://drive.google.com/file/d/1QO4kFagSs68Vgz2XZhoDbYfmhErGbK4W/view?usp=drivesdk', 'Grade 8', 'Afaan Oromoo'),
('Kitaaba og-Aarti kutaa 8ffaa', 'Digital textbook for Arts - Grade 8', 'pdf', 'https://drive.google.com/file/d/1xTwTTDXSIu4uz1h9Vp8Ahe5SgokSJqLN/view?usp=drivesdk', 'Grade 8', 'Arts'),
('Kitaaba F.J.Q kutaa 8ffaa', 'Digital textbook for F.J.Q - Grade 8', 'pdf', 'https://drive.google.com/file/d/1mLwIfhszniSmAhLokVGtT1yUdo_1LDhV/view?usp=drivesdk', 'Grade 8', 'F.J.Q'),
('Kitaaba saayinsii waliigalaa kutaa 8ffaa', 'Digital textbook for General Science - Grade 8', 'pdf', 'https://drive.google.com/file/d/1xJkMlbprZVreWtJnKwd339lyz6jYiM9m/view?usp=drivesdk', 'Grade 8', 'Saayinsii'),
('Kitaaba dhaweessumma kutaa 8ffaa', 'Digital textbook for Dhaweessumma - Grade 8', 'pdf', 'https://drive.google.com/file/d/1eidHf3f6u8g5GXSOb-IIZ-p322JMLQGt/view?usp=drivesdk', 'Grade 8', 'Dhaweessumma'),
('Kitaaba ICT kutaa 8ffaa', 'Digital textbook for ICT - Grade 8', 'pdf', 'https://drive.google.com/file/d/1QpU91CCoxcZfEw-zgTD2_OrNQ1yb3k_v/view?usp=drivesdk', 'Grade 8', 'ICT');