-- Add teaching_subject and education_level columns to profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS teaching_subject TEXT,
ADD COLUMN IF NOT EXISTS education_level TEXT;

-- Insert Grade 6 Herrega (Math) Quiz - 45 min, 30 questions
INSERT INTO public.exams (title, description, subject, grade_level, duration_minutes, total_marks, questions) VALUES (
  'Herrega - Qormaata Kutaa 6ffaa',
  'Qormaata Herregaa kutaa 6ffaa - gaaffilee 30',
  'Herrega',
  'Grade 6',
  45,
  30,
  '[
    {"id": "h1", "question": "Kankanagadiikeessa tokko hafe malee 4 fhirama kami?", "options": ["65824", "1234", "67823", "34562"], "correct_answer": 0, "marks": 1},
    {"id": "h2", "question": "Lakkoofsi hundaa kophxiita''e inni xiqqaa kami?", "options": ["1", "4", "9", "2"], "correct_answer": 0, "marks": 1},
    {"id": "h3", "question": "Lakkoofsa tarmaangadi tti kennaman keessaa kan lakkoofsa guutu hin taane kami?", "options": ["4", "40", "66", "15"], "correct_answer": 3, "marks": 1},
    {"id": "h4", "question": "Cimdi lakkoofsa tarmaangadi tti kennaman keessaa kan lakkoofsa waliif kophxiita''e kami?", "options": ["4 fi 6", "18 fi 36", "13 fi 15", "51 fi 20"], "correct_answer": 1, "marks": 1},
    {"id": "h5", "question": "Kanneen tarmaangadi keessa kan sirrii hin taane kami?", "options": ["28 hirmaa 4 ti", "35 hirmaa 5 ti", "3 hirmaataa 18 ti", "8 hirmaataa 34 ti"], "correct_answer": 3, "marks": 1},
    {"id": "h6", "question": "Adda kanta''e kami?", "options": ["13", "47", "67", "87"], "correct_answer": 0, "marks": 1},
    {"id": "h7", "question": "Xiqqaa irraa gara guddaatti yoo tartiibeesinu, maal ta''a?", "options": ["1/3, 1/2, 1/5, 3/4", "1/2, 1/3, 1/5, 3/4", "1/5, 1/3, 1/2, 3/4", "1/5, 1/2, 1/3, 3/4"], "correct_answer": 2, "marks": 1},
    {"id": "h8", "question": "HWG 180 fi 126 barbaadi?", "options": ["18", "9", "12", "14"], "correct_answer": 2, "marks": 1},
    {"id": "h9", "question": "Yoo ta''e X = ?", "options": ["3", "1", "5", "15"], "correct_answer": 0, "marks": 1},
    {"id": "h10", "question": "HWX (9,12) kanta''e kami?", "options": ["24", "27", "37", "45"], "correct_answer": 0, "marks": 1},
    {"id": "h11", "question": "Kanneen armaan gadii keessaa kan sirrii ta''e kami?", "options": ["3x + 5 = 11", "Ax + b = c", "Ax + b = 0", "3 + 4 = 7"], "correct_answer": 0, "marks": 1},
    {"id": "h12", "question": "Fractions yoota''an sirrii ta''e kami?", "options": ["1/2", "3/4", "5/8", "7/9"], "correct_answer": 1, "marks": 1},
    {"id": "h13", "question": "Kan tarmaangadi keessatti hiima wal-caalmaa kanta''e kami?", "options": ["Ax + b = c", "3x + 5 = 11", "ax + b = 0", "3 + 4 = 7"], "correct_answer": 1, "marks": 1},
    {"id": "h14", "question": "Lakkoofsa guutuu kophxiita''e kami?", "options": ["0", "1", "5", "2"], "correct_answer": 1, "marks": 1},
    {"id": "h15", "question": "4 gara fractions tti yoo jijjirru, maal ta''a?", "options": ["1/25", "23/50", "23/500", "23/100"], "correct_answer": 3, "marks": 1},
    {"id": "h16", "question": "72 hirmaattoota kophii fi nyoodiddirramee ibsamu kamta''a?", "options": ["23x31", "23x32", "24x3", "23x33"], "correct_answer": 1, "marks": 1},
    {"id": "h17", "question": "Lakkoofsa kophxiikaanta''e kami?", "options": ["69", "59", "39", "49"], "correct_answer": 0, "marks": 1},
    {"id": "h18", "question": "Hiramoottawalii 4 fi 5 kanta''e kami?", "options": ["12,20,40", "15,16,20", "32,36,40", "20,40,60"], "correct_answer": 3, "marks": 1},
    {"id": "h19", "question": "Lakkoofsa 5.6274 keessatti 7 manamee qati?", "options": ["Kumaaffaa", "Dhibbaffaa", "Kuranafaa", "Tokkooffaa"], "correct_answer": 1, "marks": 1},
    {"id": "h20", "question": "Kanneen tarmaangadi keessatti kan sirrii ta''e kami?", "options": ["1/2 < 1/4", "4/5 > 2/3", "3/4 < 2/3", "4/3 < 2/3"], "correct_answer": 1, "marks": 1},
    {"id": "h21", "question": "Deesimaalii 8.85327 gara mana kurnaffattiyoosiqsinu?", "options": ["8.8", "8.9", "9.0", "8.86"], "correct_answer": 3, "marks": 1},
    {"id": "h22", "question": "76,000 mallattoosaayinsawaa tti yoo ibsamu, akkamitti barreeffama?", "options": ["7.6x10^3", "7.6x10^5", "7.6x10^4", "7.6x10^2"], "correct_answer": 2, "marks": 1},
    {"id": "h23", "question": "Fractions sirrii kami?", "options": ["8/4", "7/3", "3/4", "12/5"], "correct_answer": 2, "marks": 1},
    {"id": "h24", "question": "Miiliyoona shanifi kuma jahaaf dhibba lamaafi sagaltamii jaha lakkoofsa kami?", "options": ["5,000,696", "50,006,296", "506,296", "5,006,296"], "correct_answer": 3, "marks": 1},
    {"id": "h25", "question": "Kanneen tarmaangadi keessatti 42/3 walqixaa hin taane kami?", "options": ["4 + 2/3", "15/3", "13/3", "14/3"], "correct_answer": 1, "marks": 1},
    {"id": "h26", "question": "0.643 - 0.325 kamta''a?", "options": ["0.318", "0.138", "0.218", "-"], "correct_answer": 0, "marks": 1},
    {"id": "h27", "question": "___?", "options": ["2/3", "6", "3", "2"], "correct_answer": 0, "marks": 1},
    {"id": "h28", "question": "Hirmaata waliiguddicha (HWG) lakkoofsota 150, 200 fi 300 meeqa?", "options": ["100", "50", "25", "150"], "correct_answer": 0, "marks": 1},
    {"id": "h29", "question": "5/4 biifaddeesimaalitti yoo ibsamuu, akkamitti barreeffama?", "options": ["7.6x10^3", "7.6x10^5", "7.6x10^4", "7.6x10^2"], "correct_answer": 2, "marks": 1},
    {"id": "h30", "question": "Kankana tarmaangadi keessaa tokko salphatee barreeffame?", "options": ["7/35", "3/15", "6/21", "8/39"], "correct_answer": 1, "marks": 1}
  ]'::jsonb
);

-- Insert Grade 6 Saayinsi Naannoo (Environment Science) Quiz - 35 min, 30 questions
INSERT INTO public.exams (title, description, subject, grade_level, duration_minutes, total_marks, questions) VALUES (
  'Saayinsi Naannoo - Qormaata Kutaa 6ffaa',
  'Qormaata Saayinsi Naannoo kutaa 6ffaa - gaaffilee 30',
  'Saayinsi Naannoo',
  'Grade 6',
  35,
  30,
  '[
    {"id": "sn1", "question": "Biyya tokko biyya biroo waliin walbira qabuun ibsuun maal jedhama?", "options": ["Argama dhugaa", "Argama bir-qabaa", "Sarara dagalee", "Sarara gadee"], "correct_answer": 1, "marks": 1},
    {"id": "sn2", "question": "Kaartaa irratti sararoota yaadaa dagaleefi gadee fayyadamuun argama iddoo tokkoo agarsiisuun maal jedhama?", "options": ["Argama dhugaa", "Argama bir-qabaa", "Kallattii", "GPS"], "correct_answer": 0, "marks": 1},
    {"id": "sn3", "question": "Garbi guddaan Hindii naannoo baha Afrikaa kallattii kamiin daangessa?", "options": ["Kaabaan", "Dhihaan", "Kaaba Bahaan", "Kibba Bahaan"], "correct_answer": 3, "marks": 1},
    {"id": "sn4", "question": "Gabaajeen ''GPS'' jedhu hiika afaan Oromootiin maal jedhama?", "options": ["Sirna Argamaa Addunyaalessaa", "Sirna Kallattii Addunyaa", "Kaartaa Googilii", "Saatilaayitii Lafaa"], "correct_answer": 1, "marks": 1},
    {"id": "sn5", "question": "Seelota dhiigaa keessaa kan oksijiiniifi kaarboondaayoksaayidii geejjibu kami?", "options": ["Seelota dhiigaa adii", "Pilaatileetota", "Seelota dhiigaa diimaa", "Pilaazmaa"], "correct_answer": 2, "marks": 1},
    {"id": "sn6", "question": "Seelota dhiigaa keessaa kan lubbu-qabeeyyii xixiqqoo dhukkuba fiduu danda''an nafarraa ittisu kami?", "options": ["Seelota dhiigaa diimaa", "Seelota dhiigaa adii", "Pilaatileetota", "Kaappilaroota"], "correct_answer": 1, "marks": 1},
    {"id": "sn7", "question": "Yeroo nafti muramu dhiigni akka ititu kan taasisu kami?", "options": ["Pilaatileetota", "Seelota dhiigaa adii", "Seelota dhiigaa diimaa", "Venaa kaavaa"], "correct_answer": 0, "marks": 1},
    {"id": "sn8", "question": "Ujummoo dhiigaa onnee irraa gara qaamolee adda addaatti dhiiga geejjibu maal jedhama?", "options": ["Ujummoo dhiiga deebistuu", "Ujummoo dhiiga raabsituu", "Kaappilaroota", "Venaa kaavaa"], "correct_answer": 1, "marks": 1},
    {"id": "sn9", "question": "Ujummoo dhiiga raabsituu keessaa inni furdaan maal jedhama?", "options": ["Venaa kaavaa", "A''oortaa", "Kaappilaroota", "Huut-sadee"], "correct_answer": 1, "marks": 1},
    {"id": "sn10", "question": "Ujummoon dhiiga deebistuu inni guddaan maal jedhama?", "options": ["A''oortaa", "Venaa kaavaa", "Kaappilaroota", "Septamii"], "correct_answer": 1, "marks": 1},
    {"id": "sn11", "question": "Onneen caasaa membireenii alaan haguugu maal jedhama?", "options": ["Periikaardiyamii", "Septamii", "Orikilii", "Ventirikilii"], "correct_answer": 0, "marks": 1},
    {"id": "sn12", "question": "Onneen namaa goloota meeqa qaba?", "options": ["Lama", "Sadii", "Afur", "Jaha"], "correct_answer": 2, "marks": 1},
    {"id": "sn13", "question": "Goloonni onnee gara olii maal jedhamu?", "options": ["Ventirikiloota", "Orikiloota", "Septamii", "Huutuuwwan"], "correct_answer": 1, "marks": 1},
    {"id": "sn14", "question": "Huutuun orikilii mirgaafi ventirikilii mirgaa gidduutti argamu maal jedhama?", "options": ["Huut-lamee", "Huut-sadee", "Septamii", "A''oortaa"], "correct_answer": 2, "marks": 1},
    {"id": "sn15", "question": "Dandeettii dalagaa dalaguu maal jedhama?", "options": ["Maashinii", "Hojii", "Anniisaa", "Saffisa"], "correct_answer": 2, "marks": 1},
    {"id": "sn16", "question": "Anniisaan nyaataa, cilee, fi naafxa keessatti argamu anniisaa akkamiiti?", "options": ["Anniisaa sochii", "Anniisaa keemikaalaa", "Anniisaa niwukulaaraa", "Anniisaa sagalee"], "correct_answer": 1, "marks": 1},
    {"id": "sn17", "question": "Anniisaan sababa sochii wantootaan argamu maal jedhama?", "options": ["Anniisaa sochii", "Anniisaa kuufamaa", "Anniisaa harkisaa", "Anniisaa keemikaalaa"], "correct_answer": 0, "marks": 1},
    {"id": "sn18", "question": "Maashinoonni yommuu humni irratti dalagaa''u faayidaa maalii qabu?", "options": ["Humna baay''isuu", "Kallattii humnaa jijjiiruu", "Saffisa baay''isuu", "Hunda deebii dha"], "correct_answer": 3, "marks": 1},
    {"id": "sn19", "question": "Maashinoonni sasalphoon akaakuu meeqa jiru?", "options": ["Afur", "Shan", "Jaha", "Torba"], "correct_answer": 2, "marks": 1},
    {"id": "sn20", "question": "Ba''aa ulfaatina guddaa qabu dirra isaa irra sochoosuun iddoo gadi aanaa irraa gara iddoo olka''aatti olbaasuuf kan gargaaru kami?", "options": ["Qottoo", "Bal''insa habalakaa", "Puulii", "Fonqolcha"], "correct_answer": 3, "marks": 1},
    {"id": "sn21", "question": "Maqasii fi ciniintuun (piinsaa) fakkeenya fonqolcha sadarkaa meeqaffaati?", "options": ["Sadarkaa tokkoffaa", "Sadarkaa lammaffaa", "Sadarkaa sadaffaa", "Sadarkaa afurffaa"], "correct_answer": 2, "marks": 1},
    {"id": "sn22", "question": "Fonqolcha sadarkaa lammaffaa keessatti gidduu kan oolu kami?", "options": ["Utubduu", "Ba''aa", "Humna sochooftuu", "Saffisa"], "correct_answer": 0, "marks": 1},
    {"id": "sn23", "question": "Wiilii geengawoo naannawaan isaa dhooqa ta''ee siiqqee handhuura isaa keessa darbu irratti walabaan naanna''u kami?", "options": ["Iskiriwuu", "Puulii", "Qottoo", "Fonqolcha"], "correct_answer": 0, "marks": 1},
    {"id": "sn24", "question": "Wantoota gargar baasuuf yookiin baqaqsuuf maashinii salphaa fayyadu kami?", "options": ["Fonqolcha", "Bal''insa habalakaa", "Qottoo", "Puulii"], "correct_answer": 1, "marks": 1},
    {"id": "sn25", "question": "Biyyoota baha Afrikaa keessaa lafti margaa baay''inaan kan itti argamu kami?", "options": ["Itoophiyaa", "Keeniyaa", "Taanzaaniyaa", "Hunda deebii dha"], "correct_answer": 3, "marks": 1},
    {"id": "sn26", "question": "Bineensota Paarkiiwwan biyyoolessaa Itoophiyaa qofa keessatti argaman keessaa tokko kami?", "options": ["Leenca", "Waaliyaa", "Arba", "Qeerransa"], "correct_answer": 1, "marks": 1},
    {"id": "sn27", "question": "Gaarri dheerina guddaa (meetira 5895) qabuufi baha Afrikaatti argamu kami?", "options": ["Raas Daashan", "Kilimaanjaaroo", "Baatuu", "Tulluu Diimtuu"], "correct_answer": 1, "marks": 1},
    {"id": "sn28", "question": "Akka seera biyya Itoophiyaatti, umurii malee heerumuun heeruma umurii waggaa meeqaa gadiiti?", "options": ["Waggaa 15", "Waggaa 16", "Waggaa 18", "Waggaa 20"], "correct_answer": 2, "marks": 1},
    {"id": "sn29", "question": "Gaa''elli ijoollee umurii waggaa kudhanii gadiin gaggeeffamu maal jedhama?", "options": ["Gaa''ela waadaa", "Gaa''ela ijoollummaa", "Gaa''ela dirqamaa", "Gaa''ela aadaa"], "correct_answer": 1, "marks": 1},
    {"id": "sn30", "question": "HIV/AIDS ittisuuf tooftaan sirrii ta''e kami?", "options": ["Of-eeggannoo gochuu", "Qorannoo dhiigaa gochuu", "Amanamummaa gaa''elaa", "Hunda deebii dha"], "correct_answer": 0, "marks": 1}
  ]'::jsonb
);

-- Insert Grade 6 Afaan Oromoo Quiz - 30 min, 30 questions
INSERT INTO public.exams (title, description, subject, grade_level, duration_minutes, total_marks, questions) VALUES (
  'Afaan Oromoo - Qormaata Kutaa 6ffaa',
  'Qormaata Afaan Oromoo kutaa 6ffaa - gaaffilee 30',
  'Afaan Oromoo',
  'Grade 6',
  30,
  30,
  '[
    {"id": "ao1", "question": "Kanneen armaan gadii keessaa kamtu sagalee dheeraa qofa qaba?", "options": ["Qaama", "Fala", "Aanaa", "Oda"], "correct_answer": 2, "marks": 1},
    {"id": "ao2", "question": "Jechi sagalee gabaabaa, dheeraa, laafaa fi jabaa qabu kami?", "options": ["Okolee", "Sabboonaa", "Diimina", "Milkii"], "correct_answer": 1, "marks": 1},
    {"id": "ao3", "question": "Hanga teessee nyaattu____ hin kaatuu?", "options": ["kutatee", "Kutate", "Kutattee", "Kutaattee"], "correct_answer": 3, "marks": 1},
    {"id": "ao4", "question": "Jaldeessi ____ bunaatti rarra''ee cabse. Waan ishee jaalattaniif ___ moggaasaa", "options": ["daamee/Daammee", "damee/Dammee", "dame/Damme", "Dammee/damee"], "correct_answer": 1, "marks": 1},
    {"id": "ao5", "question": "Waqtiilee waggaa keessaa Yeroo_____ gar-malee hoo''a.", "options": ["Boonaa", "Bona", "Boona", "Bonaa"], "correct_answer": 1, "marks": 1},
    {"id": "ao6", "question": "Inni ______ keenya jedhanii ulfina kennaniif.", "options": ["Soda", "Soddaa", "Soodaa", "Sodaa"], "correct_answer": 3, "marks": 1},
    {"id": "ao7", "question": "Horii namaa ____n seeraan nama gaafachiisa.", "options": ["Hattuu", "Haatuu", "Hatu", "Hatuu"], "correct_answer": 1, "marks": 1},
    {"id": "ao8", "question": "__malee ___n walitti hin yaa''u.", "options": ["Lagaa/laagaa", "Laagaa/laga", "Laga/laagaa", "Laaga/lagaa"], "correct_answer": 3, "marks": 1},
    {"id": "ao9", "question": "Qorumsa kana hojjechuuf yeroo kee qisaasessuu hin qabdu.", "options": ["Too''achuu", "Ilaaluu", "Mil''achuu", "Gubuu"], "correct_answer": 0, "marks": 1},
    {"id": "ao10", "question": "Qacceen qurxummii hedduudha.", "options": ["Garaftuun", "Sanyii", "Alangeen", "Hormaanni"], "correct_answer": 1, "marks": 1},
    {"id": "ao11", "question": "Ijoollee obbo Bilisaa keessaa meetiin haxxeedha", "options": ["Hattuudha", "Gamnadha", "Gowwaadha", "Colleedha"], "correct_answer": 0, "marks": 1},
    {"id": "ao12", "question": "Barattoonni kutaa 6ffaa qormaata biyyoolessaa hojjechuuf deeggarsa barbaadu.", "options": ["tumsa", "Hatuu", "Sodaa", "dheengadda"], "correct_answer": 0, "marks": 1},
    {"id": "ao13", "question": "Yoo bakkalchi bahe akka lafti bari''e hubadhu.", "options": ["Urjii ganamaa", "biiftuu ganamaa", "bakakkaa", "addeessa"], "correct_answer": 1, "marks": 1},
    {"id": "ao14", "question": "Jireenyi magaalaa kan baadiyyaarra mi''aadha", "options": ["mijataa", "Qala''aa", "Busha''aa", "rakasa"], "correct_answer": 0, "marks": 1},
    {"id": "ao15", "question": "Tolasaan jaalallee isaa soqee dhabe.", "options": ["qofforee", "barbaadee", "Fooricee", "ajjeesee"], "correct_answer": 1, "marks": 1},
    {"id": "ao16", "question": "Jechoota armaan gadii keessaa maxxantuu boodaa ''__oota'' jedhu maxxanfachuun danoomee hin dandeenye kam?", "options": ["Saree", "bilisummaa", "nama", "Harree"], "correct_answer": 1, "marks": 1},
    {"id": "ao17", "question": "Himoota armaan gadii keessaa hammattuun isa kam keessatti iddoo sirrii gale?", "options": ["Biiroon Barnoota Bulchiinsa magaalaa Finfinnee BBBMF (Caffee Araaraatti) argama.", "Angafa ofiif ulfina kabaja (kennuun) aadaa Oromooti.", "''Bor Abbaa (haadha) kee fidii koottu!'' naan jedhe barsiisaan kiyya.", "Soba dhara dubbachuun aadmaleedha."], "correct_answer": 0, "marks": 1},
    {"id": "ao18", "question": "Dhamsagoota armaan gadii keessaa dhamsaga ergisaa kan ta''e kami?", "options": ["/v/", "/c/", "/sh/", "/a/"], "correct_answer": 2, "marks": 1},
    {"id": "ao19", "question": "Dhamsagoonni walitti qindaa''uun______uumu.", "options": ["hima", "Jecha", "Sagalee", "gaalee"], "correct_answer": 1, "marks": 1},
    {"id": "ao20", "question": "Seerota birsagaa ilaalchisee sirrii kan ta''e kami?", "options": ["Birsagni qubee dachaa (ka''umsa) qofaan ni uumama", "Birsagni dubbachiiftuu (utubaa) qofaan ni uumama", "Birsagni dubbifamaa (ka''umsaa fi cufaa) qofaan ni uumama", "Birsagni dubbifamaa (cufaa) qofaan ni uumama"], "correct_answer": 2, "marks": 1},
    {"id": "ao21", "question": "Jechoota armaan gadii keessaa kan birsaga shan qabu kami?", "options": ["Caccabsaa", "barreeffama", "Malaammaltummaa", "Mirkaneesse"], "correct_answer": 0, "marks": 1},
    {"id": "ao22", "question": "Caacculee keeyyataa keessaa yaada barreessaan keeyyata sana keessatti dabarfachuu barbaade yaada dimshaashaa fi handhuuraa ta''e kan of keessatti qabatu kami?", "options": ["Hima ijoo", "Hima goolabaa", "Hima callaa", "Hima gargaartuu"], "correct_answer": 0, "marks": 1},
    {"id": "ao23", "question": "Jechi Bilisummaa jedhu dhamsagoota meeqarraa ijaarame?", "options": ["8", "10", "7", "11"], "correct_answer": 1, "marks": 1},
    {"id": "ao24", "question": "Caasaalee keeyyataa keessaa gaaffilee hima ijoo keessatti ka''aniif deebii kan laatu kami?", "options": ["Hima sensaa", "Hima goolabaa", "Hima callaa/gargaartuu", "Hima ijoo"], "correct_answer": 1, "marks": 1},
    {"id": "ao25", "question": "Gaaromsaan kaleessa Adaamaa deeme. Hima jedhu keessatti gochibsi yeroo kami?", "options": ["Kaleessa", "Adaamaa", "deeme", "Gaaromsaan"], "correct_answer": 2, "marks": 1},
    {"id": "ao26", "question": "Kanneen armaan gadii keessaa kamtu maqaa dimshaashaa miti?", "options": ["Hoomaa", "Bineelda", "Koree", "Birbirsa"], "correct_answer": 3, "marks": 1},
    {"id": "ao27", "question": "Kanneen armaan gadii keessaa kamtu maqaa dhuunfaati?", "options": ["Ummata", "Albuuda", "Baargamoo", "Bineelda"], "correct_answer": 2, "marks": 1},
    {"id": "ao28", "question": "Balaan humna ibsaa har''a Magaalaa Finfinneetti uumame lubbuu namoota hedduu galaafate.", "options": ["balleesse", "baraare/oolche", "dabarse", "Fixe"], "correct_answer": 1, "marks": 1},
    {"id": "ao29", "question": "Guddinni biyya tokkoo akka laayyootti hin dhufu", "options": ["arjaa", "Salphaa", "Kaayyoo", "cimaa"], "correct_answer": 3, "marks": 1},
    {"id": "ao30", "question": "Qotiyyoon Obbo Guddinaan gurgure colleedha.", "options": ["Ciisaa", "daagii", "Saffisaa", "dadhabaa"], "correct_answer": 1, "marks": 1}
  ]'::jsonb
);

-- Insert Grade 6 Safuu (Ethics) Quiz - 30 min, 30 questions
INSERT INTO public.exams (title, description, subject, grade_level, duration_minutes, total_marks, questions) VALUES (
  'Safuu - Qormaata Kutaa 6ffaa',
  'Qormaata Safuu kutaa 6ffaa - gaaffilee 30',
  'Safuu',
  'Grade 6',
  30,
  30,
  '[
    {"id": "sf1", "question": "Miidhaa dhabamuun amanamummaa safuu fiduu danda''u isa kami?", "options": ["Sobni baay''achuu", "Hannaafi gowwomsaa", "Ajaja fudhachuu dhabuu", "Hunduu deebiidha"], "correct_answer": 3, "marks": 1},
    {"id": "sf2", "question": "Hawaasa amanamummaa safuu qaburraa ijaarame maaltu irraa eegama?", "options": ["hariiroo lafaa qabu", "waadaa hin kabajaan", "aadaa hojii cimaa qabu", "faayidaa namoota irraa eegatu"], "correct_answer": 2, "marks": 1},
    {"id": "sf3", "question": "Duudhaalee namoota amanamummaa safuu qabanii kan ta''e isa kami?", "options": ["Kutannoo qabachuu", "Namaaf yaaduu dhabuu", "of tuulummaa", "Deebiin hin kennamne"], "correct_answer": 0, "marks": 1},
    {"id": "sf4", "question": "Ibsiitoota amala gaariin qabu keessaa inni tokko isa kami?", "options": ["haqummaa", "Seera", "Of kabajuu", "Maatii"], "correct_answer": 2, "marks": 1},
    {"id": "sf5", "question": "__ Nama dhugaa qabeessaa ta''eefi qajeelfamoota iddoo ol aanaa qabuudha.", "options": ["Filaannoo", "Haqummaa", "Safuu", "aadaa"], "correct_answer": 1, "marks": 1},
    {"id": "sf6", "question": "Feedhii miiraa ykn hawwii hawaasni gocha akka malee of eeguu kan ibsu kami?", "options": ["Abboomamummaa", "Of to''achuu", "Amanamummaa", "Itti gaafatamummaa"], "correct_answer": 1, "marks": 1},
    {"id": "sf7", "question": "Amala dhugaa dubbachuu fi hojjechuun qabu kan ibsu isa kami?", "options": ["kabajaa kennuu", "Of kabajuu", "Amanamummaa", "Deebii hin qabu"], "correct_answer": 2, "marks": 1},
    {"id": "sf8", "question": "Amaloota namoota amanamummaa qabani kan ta''e isa kami?", "options": ["Dhugaa dubbachuu", "Hannaa jibbuu", "Amanamummaa ol aanaa qabaachuu", "Hunduu deebii sirriidha"], "correct_answer": 2, "marks": 1},
    {"id": "sf9", "question": "Amalli gaariin karaa kamiin dagaaaguu danda''aa?", "options": ["wadaa kabajuu", "Hannaa", "Sobuun", "Qajeelfama cabsuun"], "correct_answer": 0, "marks": 1},
    {"id": "sf10", "question": "Namni of to''achuu danda''uu dandeetti akkamii qaba?", "options": ["Yaaduu", "Sobu", "Dhuguu", "Hunduu sirriidha"], "correct_answer": 3, "marks": 1},
    {"id": "sf11", "question": "Seerri qaama dambii fi ittiin bulmaataa ta''e walii galtee qaamoolee kamiin kan tumameedha?", "options": ["Mootummaa", "Poolisii", "Uummataa", "Afi C"], "correct_answer": 2, "marks": 1},
    {"id": "sf12", "question": "Wal amantaa uummataa fi mootummaa gidduu jiru kan balleessuu isa kami?", "options": ["Of kabajuu", "Seera cabsuu", "Seera eeguu", "Wadaa kabajuu"], "correct_answer": 1, "marks": 1},
    {"id": "sf13", "question": "Duudhaalee safuu hawaasni Itoophiyaa waliin qaban kan ibsu isa kami?", "options": ["Keessummaa jibbuu", "Dhugaa dubbachuu", "Of tuullummaa", "Walqixxummaa cabsuu"], "correct_answer": 1, "marks": 1},
    {"id": "sf14", "question": "Kamtuu miidhaa dhabamuu amala gaarii geessiisaa?", "options": ["Kijibuu", "Walreebu", "Hatuu", "Hunduu sirriidha"], "correct_answer": 3, "marks": 1},
    {"id": "sf15", "question": "Kanneen armaan gadii keessaa sochiilee hawaasummaa kan ta''e isa kami?", "options": ["Gareen qayyabannaa", "Immaa na nyaachuu", "Mirga namummaa", "Dhuunfaan hojjechuu"], "correct_answer": 2, "marks": 1},
    {"id": "sf16", "question": "Kamtuu sochiilee dinagdee mul''isaa?", "options": ["Hojii qonnaa", "Hojii daldalaa", "Horsiisa beeyladaa", "Hunda"], "correct_answer": 3, "marks": 1},
    {"id": "sf17", "question": "Hojii sochiilee dinagdee kan hin taane kami?", "options": ["Jaalala biyyaa", "Amantaa", "Galii argachuu", "Afi B"], "correct_answer": 1, "marks": 1},
    {"id": "sf18", "question": "Garee uummataa walitti dhuufeenya eenyummaa waloo jechuun maal jechuudha?", "options": ["aadaa", "amantaa", "hawaasa", "hunda"], "correct_answer": 2, "marks": 1},
    {"id": "sf19", "question": "Yeroo fi humna ofii fedhiidhaan gocha hawaasa fayyaduu oolchuun maal jedham?", "options": ["Duudhaa", "Amala", "Tola ooltummaa", "Hawaasa"], "correct_answer": 2, "marks": 1},
    {"id": "sf20", "question": "Tola ooltummaan hawaasaan rawwataman maal fa''i?", "options": ["harka qalleeyyii gargaaru", "namoota beela''an nyaachiisuu", "gorsa bilisaan kennuu", "hunduu sirriidha"], "correct_answer": 3, "marks": 1},
    {"id": "sf21", "question": "Barbaachisummaan seera kabajuu kan ta''e isa kami?", "options": ["Wal qixxummaa sarbuu", "Nageenya kabachiisuuf", "Malaanmaltummaa hojjechuuf", "Birmadummaan akka hin jiraaneef"], "correct_answer": 1, "marks": 1},
    {"id": "sf22", "question": "Yeroo boqonnaa hojiilee akkamiitu hojjeetamaa?", "options": ["fira gaafachuu", "kitaabilee dubbisuu", "bashannanaa", "hunduu deebiidha"], "correct_answer": 2, "marks": 1},
    {"id": "sf23", "question": "Dhaabbatni namootni ollaa yeroo rakkoo ittiin wal gargaaruuf hundaa''e kami?", "options": ["Daboo", "Iqqubbi", "Afoosha", "Jigii"], "correct_answer": 1, "marks": 1},
    {"id": "sf24", "question": "Galii gibira irraa argamuun mootummaan bu''uuraalee misoomaa kanneen akkami fa''a guutuu danda''aa?", "options": ["Daandii", "Ibsaa", "Barnoota", "Hunda"], "correct_answer": 3, "marks": 1},
    {"id": "sf25", "question": "Bakka adeemsi bituu fi gurguruu akkasumas wal jijjiiraan meeshaalee itti", "options": ["daldalaa", "qusannaa", "bittinneessuu", "hunda"], "correct_answer": 0, "marks": 1},
    {"id": "sf26", "question": "Barbaachiisummaan gibira kaffaluu maalii?", "options": ["qusaannoof", "of guddisuuf", "namoota dhuunfaa gargaaruuf", "mootummaa mallaqaan gargaaruuf"], "correct_answer": 3, "marks": 1},
    {"id": "sf27", "question": "Waan itti fayyadamnu hunda qisaasessuurraa irraa ol kawwachuu kan ibsu kami?", "options": ["daldalaa", "qusannaa", "bittinneessuu", "hunda"], "correct_answer": 1, "marks": 1},
    {"id": "sf28", "question": "Shaambal Abbabaan Oolompikii Roomaa kan injifate bara kami?", "options": ["1932", "1974", "1956", "1900"], "correct_answer": 2, "marks": 1},
    {"id": "sf29", "question": "Kanneen armaan gadii keessaa tokko madda galii mootummaa isa ol aanaadha?", "options": ["gibira", "turiizimii", "daldala", "gabaa"], "correct_answer": 0, "marks": 1},
    {"id": "sf30", "question": "Amala safuu hawaasaa fi namoota irratti hojjechuu kan agarsiisu?", "options": ["Amanamummaa", "Of to''achuu", "Tola ooltummaa", "Hunduu sirriidha"], "correct_answer": 2, "marks": 1}
  ]'::jsonb
);

-- Insert Grade 6 Amharic Quiz - 35 min, 30 questions
INSERT INTO public.exams (title, description, subject, grade_level, duration_minutes, total_marks, questions) VALUES (
  'አማርኛ - የ6ኛ ክፍል ፈተና',
  'የአማርኛ ቋንቋ የ6ኛ ክፍል ፈተና - 30 ጥያቄዎች',
  'Amharic',
  'Grade 6',
  35,
  30,
  '[
    {"id": "am1", "question": "ፈረስ ማደ --------- ባላል", "options": ["ጋ", "ጉ", "በ", "ፈ"], "correct_answer": 0, "marks": 1},
    {"id": "am2", "question": "በጎች ማደ --------- ባላል", "options": ["ጋ", "ጉ", "በ", "መ"], "correct_answer": 1, "marks": 1},
    {"id": "am3", "question": "እናትና አባት አንድ ላይ -------- ይባላሉ", "options": ["አጎት", "አክስት", "ወላጆች", "ንድም"], "correct_answer": 2, "marks": 1},
    {"id": "am4", "question": "''ደብዳቤ'' በሚለው ቃል አፍ ነገር ማን ነው?", "options": ["እ", "ፈች", "ደብዳቤ", "መልዕክት"], "correct_answer": 2, "marks": 1},
    {"id": "am5", "question": "''እና ሀኪምና'' በሚለው አፍ ነገር ማን ነው?", "options": ["ሀኪም", "ና", "እና", "ሁሉም"], "correct_answer": 3, "marks": 1},
    {"id": "am6", "question": "ከመካከሉ ላይ የሚያመለክት ቃል የትኛው ነው?", "options": ["ጀርባ", "እ", "መና", "በ"], "correct_answer": 3, "marks": 1},
    {"id": "am7", "question": "በመልካም ጋብቻ የሚጠራ ስም -------- ይባላል", "options": ["ባዳ", "ጎቤ", "መድ", "ሁሉም"], "correct_answer": 1, "marks": 1},
    {"id": "am8", "question": "ባህልና ልማድ የሀገር -------- ነው", "options": ["አካል", "አጎ", "መለያ", "ቢጫ"], "correct_answer": 2, "marks": 1},
    {"id": "am9", "question": "ባህላዊ ጎጆ ቤት -------- ነው", "options": ["ጎን", "አማን", "ክብ", "አምባ"], "correct_answer": 2, "marks": 1},
    {"id": "am10", "question": "እህል የሚከማችበት -------- ይባላል", "options": ["በመል", "ጎ", "ጋን", "ና"], "correct_answer": 2, "marks": 1},
    {"id": "am11", "question": "ምምክ የሚባለው -------- ነው", "options": ["ምዕላድ", "ልምድ", "መግቢያ", "ግ"], "correct_answer": 1, "marks": 1},
    {"id": "am12", "question": "ለልብ የሚፈልግ -------- ነው", "options": ["ልብ", "አእምሮ", "አፈ", "ጭንቅ"], "correct_answer": 2, "marks": 1},
    {"id": "am13", "question": "ማከም ከ -------- ጋር ይዛመዳል", "options": ["ንብ", "ን", "ንብረት", "ንጫ"], "correct_answer": 0, "marks": 1},
    {"id": "am14", "question": "ጋና እንላል የትኛው እንስሳ ነው?", "options": ["ግመል", "ዶሮ", "ድመት", "በግ"], "correct_answer": 1, "marks": 1},
    {"id": "am15", "question": "''እነ ነገመ'' የትኛው ዓይነት ቃል ነው?", "options": ["ስም", "መደብ", "ግስ", "ግል"], "correct_answer": 1, "marks": 1},
    {"id": "am16", "question": "''እማነ'' የትኛው ዓይነት ቃል ነው?", "options": ["ስም", "ተውላጠ", "መደብ", "አምላ"], "correct_answer": 2, "marks": 1},
    {"id": "am17", "question": "ምግብ ብሎ መገበ፤ ጨ ብሎ -------- ይባላል", "options": ["አጫ", "ጫ", "ጨ", "ማጫ"], "correct_answer": 2, "marks": 1},
    {"id": "am18", "question": "ልጅን መምረቅ -------- አስፈላጊ ነው", "options": ["ግን", "ቢሆንም", "ለህ", "ምንም"], "correct_answer": 2, "marks": 1},
    {"id": "am19", "question": "ለአማጭ የሚገለግል -------- ነው", "options": ["ለህ", "ም", "ምክንያት", "እንጂ"], "correct_answer": 2, "marks": 1},
    {"id": "am20", "question": "''ብ'' የሚለው ምን ዓይነት ድምፅ ነው?", "options": ["ንፋስ", "ችሎ", "ዝምታ", "ጩኸት"], "correct_answer": 0, "marks": 1},
    {"id": "am21", "question": "በአፍ ነገር ውስጥ ጊዜ የሚያመለክት -------- ነው", "options": ["ባለቤት", "ቢ", "ግስ", "ማን"], "correct_answer": 2, "marks": 1},
    {"id": "am22", "question": "''እኔ'' የትኛው መደብ ነው?", "options": ["እ", "እኔ", "እነ", "አን"], "correct_answer": 1, "marks": 1},
    {"id": "am23", "question": "ሁለት ከሁለት በላይ ያሉ ምዕላዶች -------- ይባላሉ", "options": ["ብብ", "ደብ", "ነላ", "ሁሉም"], "correct_answer": 3, "marks": 1},
    {"id": "am24", "question": "ንባብ በመማር ልምድ ማግኘት -------- ነው", "options": ["ጥሩ", "መካከለኛ", "ክፉ", "ደካማ"], "correct_answer": 0, "marks": 1},
    {"id": "am25", "question": "መሀበረሰብ ሀገርን እንዲፋፋ -------- ነው", "options": ["መሠረት", "በሀገር", "እፋፋነ", "ሁሉም"], "correct_answer": 3, "marks": 1},
    {"id": "am26", "question": "ግዴለኛ ሰው -------- ነው", "options": ["በካ", "ቸልኛ", "ፈጣን", "ሁሉም"], "correct_answer": 1, "marks": 1},
    {"id": "am27", "question": "ሚከተለው ትክክለኛ ቃል የትኛው ነው?", "options": ["ሚ", "ሚፋ", "ሁሉ", "መልስ"], "correct_answer": 3, "marks": 1},
    {"id": "am28", "question": "ፈ -------- የተሟላ ሀረግ ነው", "options": ["ፈ", "በፈለ", "ሌለ", "ሁሉም"], "correct_answer": 2, "marks": 1},
    {"id": "am29", "question": "''አደጋ'' ማለት -------- ማለት ነው", "options": ["ጉዳት", "ደስታ", "ሀብት", "ሀናለ"], "correct_answer": 0, "marks": 1},
    {"id": "am30", "question": "''እሉ'' በአፍ ነገር -------- ይሆናል", "options": ["በንእ", "እ", "እመ", "መልስ"], "correct_answer": 3, "marks": 1}
  ]'::jsonb
);

-- Insert Grade 6 English Quiz - 30 min, 30 questions
INSERT INTO public.exams (title, description, subject, grade_level, duration_minutes, total_marks, questions) VALUES (
  'English - Grade 6 Exam',
  'English Language Grade 6 Exam - 30 questions',
  'English',
  'Grade 6',
  30,
  30,
  '[
    {"id": "en1", "question": "They must ---------------- the traffic rules.", "options": ["break", "obey", "disobey", "expect"], "correct_answer": 1, "marks": 1},
    {"id": "en2", "question": "Where do they usually ---------------- the new year, at home or outside home?", "options": ["celebrate", "dance", "visit", "see"], "correct_answer": 0, "marks": 1},
    {"id": "en3", "question": "My grandfather always advises me to be kind and -------- what I have to the poor.", "options": ["hide", "share", "keep", "take"], "correct_answer": 1, "marks": 1},
    {"id": "en4", "question": "Bekele is an intelligent student. Intelligent means:", "options": ["Clever", "dull", "happy", "lazy"], "correct_answer": 0, "marks": 1},
    {"id": "en5", "question": "Success in agriculture comes from understanding the climate. Climate means:", "options": ["Creatures", "Weather condition", "soil texture", "Crop production"], "correct_answer": 1, "marks": 1},
    {"id": "en6", "question": "The accident was occurred on the big road by vehicles. Accident means:", "options": ["an unpleasant event", "Interaction", "Pollution", "hunting"], "correct_answer": 0, "marks": 1},
    {"id": "en7", "question": "\"A good reader is a leader,\" said the person. Reader means:", "options": ["A person who reads different books", "Newspapers", "Magazines", "Book"], "correct_answer": 0, "marks": 1},
    {"id": "en8", "question": "----------- they wash their clothes?", "options": ["Is", "Do", "Has", "Does"], "correct_answer": 1, "marks": 1},
    {"id": "en9", "question": "When her mother entered the room, she -------- the wot.", "options": ["was cook", "is cooking", "was cooking", "are cooking"], "correct_answer": 2, "marks": 1},
    {"id": "en10", "question": "This is the -------- mark I have ever got.", "options": ["most", "highest", "high", "higher"], "correct_answer": 1, "marks": 1},
    {"id": "en11", "question": "She -------- speak Arabic.", "options": ["can", "was able to", "is", "could"], "correct_answer": 0, "marks": 1},
    {"id": "en12", "question": "Tola: Have you ever seen Math''s teacher? Dandi: No, I haven''t. He -------- at staff.", "options": ["must be", "may be", "should be", "can be"], "correct_answer": 1, "marks": 1},
    {"id": "en13", "question": "Students -------- read their text book to pass their exam.", "options": ["have to", "should", "ought to", "will"], "correct_answer": 0, "marks": 1},
    {"id": "en14", "question": "I -------- sport teacher in the market yesterday.", "options": ["sees", "seen", "saw", "have seen"], "correct_answer": 2, "marks": 1},
    {"id": "en15", "question": "------------ were you born?", "options": ["Why", "When", "Where", "Whose"], "correct_answer": 2, "marks": 1},
    {"id": "en16", "question": "The mobile is ringing. I -------- it.", "options": ["will answer", "am answering", "going to", "answer"], "correct_answer": 0, "marks": 1},
    {"id": "en17", "question": "Gemechu is -------- than Bekele.", "options": ["tall", "taller", "tallest", "shortest"], "correct_answer": 1, "marks": 1},
    {"id": "en18", "question": "He -------- in Addis International Bank.", "options": ["working", "work", "works", "work"], "correct_answer": 2, "marks": 1},
    {"id": "en19", "question": "The students haven''t learned Civic -------- December 21, 2021.", "options": ["for", "since", "just", "already"], "correct_answer": 1, "marks": 1},
    {"id": "en20", "question": "If you eat fruit and vegetables, you --------", "options": ["will be healthier", "would be healthier", "would have healthier", "should be healthier"], "correct_answer": 0, "marks": 1},
    {"id": "en21", "question": "I -------- class when I was six years old.", "options": ["starts", "start", "starting", "started"], "correct_answer": 3, "marks": 1},
    {"id": "en22", "question": "He -------- speaks Afan Oromo -------- he -------- speak English and Amharic.", "options": ["can / but / can", "can''t / but / can''t", "can / and / can''t", "can / but / can''t"], "correct_answer": 3, "marks": 1},
    {"id": "en23", "question": "The Professor has -------- a number of books on education.", "options": ["wrote", "written", "writing", "writes"], "correct_answer": 1, "marks": 1},
    {"id": "en24", "question": "I met him while he -------- for a bus.", "options": ["is waiting", "was waiting", "has waited", "was wait"], "correct_answer": 1, "marks": 1},
    {"id": "en25", "question": "Before you start doing this exam, -------- carefully.", "options": ["use mobile phone", "brush your teeth", "read the instruction", "do your homework"], "correct_answer": 2, "marks": 1},
    {"id": "en26", "question": "Our English teacher -------- give us an assignment today, but I am not sure.", "options": ["must", "should", "may", "ought to"], "correct_answer": 2, "marks": 1},
    {"id": "en27", "question": "She found the duster -------- she had left it.", "options": ["when", "where", "why", "which"], "correct_answer": 1, "marks": 1},
    {"id": "en28", "question": "------------ do you usually watch football?", "options": ["Why", "Where", "Who", "When"], "correct_answer": 3, "marks": 1},
    {"id": "en29", "question": "Active: Children eat some mangoes. Passive: Some mangoes -------- by children.", "options": ["are eaten", "were eaten", "are being eaten", "have been eaten"], "correct_answer": 0, "marks": 1},
    {"id": "en30", "question": "Do you know Bontu? I sit with --------.", "options": ["she", "her", "hers", "herself"], "correct_answer": 1, "marks": 1}
  ]'::jsonb
);