// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdlugfyvocudumhdescp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkbHVnZnl2b2N1ZHVtaGRlc2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDQ1MTUsImV4cCI6MjA3NDYyMDUxNX0.9s0BNS2VVGGinmW186qcM8Dz0WOV-NpJaUkccuw2qXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});